language: node_js
node_js: "0.10"
before_install: npm install --global gulp
install: npm install
after_script: ./node_modules/.bin/gulp coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
